#!/usr/bin/env node

var shelljs = require('shelljs');
var CLIEngine = require('eslint').CLIEngine;

var cli = new CLIEngine({
  envs: ["node"],
  useEslintrc: true
});

var getStagedFilesCommand = 'git diff-index --name-only HEAD';

shelljs.exec(getStagedFilesCommand, {
  silent: true
}, function(code, output) {
  if (output) {
    var files = output.split(/\r|\n|\r\n/);

    // we only need js related files
    files = files.filter(function(path) {
      return path.match(/\.js$/);
    });

    var report = cli.executeOnFiles(files);
    var formatter = cli.getFormatter();
    console.log(formatter(report.results));

    // TODO
    // temporay hack, normally this should be non-zero
    process.exit(0);
  }
  else {
    process.exit(0);
  }
});
